---
- name: Install Docker YUM repository
  yum_repository:
    name: Docker
    description: Official Docker repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: True
    keepcache: 0

- name: Install Docker Engine
  package: name=docker-engine state=present update_cache=True

- name: Enable and start Docker Engine
  service: name=docker state=started enabled=yes

- name: Install docker-py
  pip:
    executable: /usr/local/bin/pip3
    name: docker-py
    state: present