---
- name: Install package prerequisites
  package: name={{ item }} state=present
  with_items:
    - yum-utils

- name: Install build dependencies
  command: yum-builddep -y python

- name: Download and unarchive Python {{ python_version }} source code
  unarchive:
    src: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz"
    dest: "{{ home_dir }}"
    remote_src: True
    copy: False

- name: Make the directory where Python will be installed
  file: path={{ python_path }} state=directory

- name: Configure, make, and install Python from source
  command: "{{ item }}"
  with_items:
    - ./configure --prefix=/usr/local
    - make
    - make install
  args:
    chdir: "{{ python_source_dir }}"

- name: Get the Python version number
  command: python3 --version
  become: True
  become_user: vagrant
  register: installed_version

- name: Validate Python 3 is installed
  assert:
    that: "'{{ python_version }}' in '{{ installed_version.stdout }}'"

- name: Get the Pip version number
  command: pip3 --version
  become: True
  become_user: vagrant
  register: installed_version

- name: Validate Pip is installed
  assert:
    that: "'{{ python_version_major }}.{{ python_version_minor }}' in '{{ installed_version.stdout }}'"
